dna_strand='TCCAGACGTGCACGTACTTATACCATGACAGTGAAGGCTTCAGAGTATGTTAAATGCACAATAGGCACAGAGGATGCTACTTACGGTTATGTTATTCGCTGTCACGTCAGTCTAATATGGTGCGCGTGCGTTTTTCCGTCGCCATGCCAATCAACCTATGGTAGTAACCCAATCCAATCGCAACGATAGGCGTGATATCCTCCTACGAAGAACGGAACCTCAGTTCTCAATATATCACCCAGGCATAGATGATATCCCAGGGATATTCGCTTTGAGAATGCGATCCACGTCCAAAACCCCCTGGGTGCTTACGAATTCCCAGTTCGCCGGCCATATATGTGGTAGTTATGGGCCTCTCTCGTGTTAGGAGCTTGCCTACGGGTTGACCTGGTTCCCGAATTCAACGTCTTTGTTGCGAAAAGCCGAGCTTCTCGCGATCGAAGAGCCAATCAGTGAAGGCCTAGGCAGCCGCAAGCAGTTACGGTAAACGCTCACTGGTATCGCCTCGAATTATCTATGCCCAGGGACTACTCCAAAAACAGTTGTTCGCACGTCCAACGCGGATGTGCTAGATACATCAGGTTGATAGGTACGTTAGGTCCCGGTGGCGAGCATTTAAGACCAGACTCTTATGGGGGAGTCGTGGTGCCCGCACCAAGTCCGCCGGGAGCCGAATGCGAGCGCAAGCGAGTTTGGTCGTTCGTTCAGGCAGATATCAGAGTATGATTGGGACGTCAGAGCTTATGTTCGACTAAGATTAGTTACAAAAATGATGTAGCATACCTAACAATGCTTATATAGTAAAATAGC' # initial string

dna_strand = list(dna_strand)
dna_strand = dna_strand[::-1] # slicing 
dna_strand = ''.join(dna_strand) #rejoin the strings

return_string = ''


for i, s in enumerate(dna_strand): 
    if (s == 'A'):
      return_string += 'T'
    if (s == 'C'):
      return_string += 'G'
    if (s == 'G'):
      return_string += 'C'
    if (s == 'T'):
      return_string += 'A'

print(return_string)